export const CABINET_COPY = {
  en: {
    nav: ["Overview", "Transactions", "Monthly plan", "Recurring", "Goals", "Crypto", "Analytics"],
    shell: { personal: "PERSONAL SPACE", plan: "plan", settings: "Settings", back: "Back to home", signout: "Sign out", activity: "Activity", shortPlan: "Plan", more: "More", offline: "You’re offline. Saved data is still available; changes need a connection." },
    settings: { eyebrow: "ACCOUNT", title: "Settings", intro: "Control your profile, language, privacy, currency and membership.", display: "DISPLAY & ALERTS", language: "INTERFACE LANGUAGE", profile: "PROFILE", upload: "Upload photo", save: "Save name", saving: "Saving…", membership: "MEMBERSHIP", widgets: "DASHBOARD WIDGETS", choose: "Choose what matters", focused: "Keep the overview focused on the information you use most.", data: "YOUR DATA", backup: "Backup and restore", deleteLabel: "ACCOUNT REMOVAL", deleteTitle: "Delete account" },
    entry: { edit: "EDIT TRANSACTION", fresh: "NEW TRANSACTION", update: "Update entry", log: "Log an entry", reading: "Reading receipt…", scan: "Scan a receipt", scanHelp: "Take a photo or choose one from your library", type: "Type", expense: "Expense", income: "Income", merchant: "Merchant or source", amount: "Amount", date: "Date", category: "Category", tags: "Tags", note: "Note", optional: "Optional context", review: "Mark as needing review", saving: "Saving…", save: "Save transaction" },
    notices: { title: "Notifications", attention: (n) => `${n} item${n === 1 ? "" : "s"} need attention`, calm: "Everything looks calm", empty: "No overdue bills or budget warnings.", shown: "Amounts shown in", privacy: "privacy mode is on", post: "Post" },
  },
  pl: {
    nav: ["Pulpit", "Transakcje", "Plan miesięczny", "Cykliczne", "Cele", "Krypto", "Analizy"],
    shell: { personal: "TWOJA PRZESTRZEŃ", plan: "plan", settings: "Ustawienia", back: "Wróć na stronę", signout: "Wyloguj się", activity: "Aktywność", shortPlan: "Plan", more: "Więcej", offline: "Jesteś offline. Zapisane dane są dostępne, ale zmiany wymagają połączenia." },
    settings: { eyebrow: "KONTO", title: "Ustawienia", intro: "Zarządzaj profilem, językiem, prywatnością, walutą i planem.", display: "WYGLĄD I ALERTY", language: "JĘZYK INTERFEJSU", profile: "PROFIL", upload: "Dodaj zdjęcie", save: "Zapisz nazwę", saving: "Zapisywanie…", membership: "PLAN", widgets: "WIDŻETY PULPITU", choose: "Wybierz najważniejsze", focused: "Zostaw na pulpicie tylko informacje, z których korzystasz.", data: "TWOJE DANE", backup: "Kopia i przywracanie", deleteLabel: "USUNIĘCIE KONTA", deleteTitle: "Usuń konto" },
    entry: { edit: "EDYTUJ TRANSAKCJĘ", fresh: "NOWA TRANSAKCJA", update: "Zaktualizuj wpis", log: "Dodaj wpis", reading: "Odczytywanie paragonu…", scan: "Zeskanuj paragon", scanHelp: "Zrób zdjęcie lub wybierz je z biblioteki", type: "Typ", expense: "Wydatek", income: "Przychód", merchant: "Sprzedawca lub źródło", amount: "Kwota", date: "Data", category: "Kategoria", tags: "Tagi", note: "Notatka", optional: "Opcjonalny kontekst", review: "Oznacz do sprawdzenia", saving: "Zapisywanie…", save: "Zapisz transakcję" },
    notices: { title: "Powiadomienia", attention: (n) => `${n} elementów wymaga uwagi`, calm: "Wszystko wygląda dobrze", empty: "Brak zaległych rachunków i ostrzeżeń budżetowych.", shown: "Kwoty w", privacy: "tryb prywatny jest włączony", post: "Dodaj" },
  },
  uk: {
    nav: ["Огляд", "Транзакції", "Місячний план", "Регулярні", "Цілі", "Крипто", "Аналітика"],
    shell: { personal: "ОСОБИСТИЙ ПРОСТІР", plan: "план", settings: "Налаштування", back: "На головну", signout: "Вийти", activity: "Активність", shortPlan: "План", more: "Більше", offline: "Ви офлайн. Збережені дані доступні, але для змін потрібне з’єднання." },
    settings: { eyebrow: "АКАУНТ", title: "Налаштування", intro: "Керуйте профілем, мовою, приватністю, валютою та підпискою.", display: "ВИГЛЯД І СПОВІЩЕННЯ", language: "МОВА ІНТЕРФЕЙСУ", profile: "ПРОФІЛЬ", upload: "Додати фото", save: "Зберегти ім’я", saving: "Збереження…", membership: "ПІДПИСКА", widgets: "ВІДЖЕТИ ОГЛЯДУ", choose: "Оберіть головне", focused: "Залиште в огляді лише найважливішу для вас інформацію.", data: "ВАШІ ДАНІ", backup: "Резервна копія", deleteLabel: "ВИДАЛЕННЯ АКАУНТА", deleteTitle: "Видалити акаунт" },
    entry: { edit: "РЕДАГУВАННЯ ТРАНЗАКЦІЇ", fresh: "НОВА ТРАНЗАКЦІЯ", update: "Оновити запис", log: "Додати запис", reading: "Розпізнавання чека…", scan: "Сканувати чек", scanHelp: "Зробіть фото або виберіть його з галереї", type: "Тип", expense: "Витрата", income: "Дохід", merchant: "Продавець або джерело", amount: "Сума", date: "Дата", category: "Категорія", tags: "Теги", note: "Нотатка", optional: "Необов’язковий контекст", review: "Позначити для перевірки", saving: "Збереження…", save: "Зберегти транзакцію" },
    notices: { title: "Сповіщення", attention: (n) => `${n} елементів потребують уваги`, calm: "Все виглядає добре", empty: "Немає прострочених рахунків чи бюджетних попереджень.", shown: "Суми у", privacy: "режим приватності ввімкнено", post: "Додати" },
  },
};

const PAGE_TRANSLATIONS = {
  pl: {
    "SAFE TO SPEND": "BEZPIECZNIE DO WYDANIA", DAY: "DZIEŃ", "reserved for upcoming bills": "zarezerwowane na nadchodzące rachunki", "Add transaction": "Dodaj transakcję",
    SPENT: "WYDATKI", "MONTH-END FORECAST": "PROGNOZA NA KONIEC MIESIĄCA", INCOME: "PRZYCHODY", PLANNED: "ZAPLANOWANE", of: "z", budget: "budżetu", above: "powyżej", within: "w ramach", "current plan": "obecnego planu", "logged this month": "w tym miesiącu", "across category envelopes": "w kategoriach",
    "LAST 7 DAYS": "OSTATNIE 7 DNI", "Daily spending rhythm": "Rytm codziennych wydatków", "View analytics": "Zobacz analizy", "TREK SIGNAL": "SYGNAŁ TREK", "Your current pace is above plan": "Twoje obecne tempo przekracza plan", "Your current pace is inside plan": "Twoje obecne tempo mieści się w planie", "Review plan": "Sprawdź plan", "Ask the coach": "Zapytaj coacha", "RECENT TRANSACTIONS": "OSTATNIE TRANSAKCJE", "Latest activity": "Ostatnia aktywność", "No activity yet": "Brak aktywności", "All transactions": "Wszystkie transakcje", "TOP GOAL": "GŁÓWNY CEL", "Create your first goal": "Utwórz pierwszy cel", "Give your monthly plan a direction.": "Nadaj kierunek swojemu miesięcznemu planowi.", "Open goals": "Otwórz cele",
    "YOUR RECORDS": "TWOJE WPISY", Transactions: "Transakcje", "visible entries": "widocznych wpisów", "edit, filter or review your records.": "edytuj, filtruj i sprawdzaj wpisy.", "Search merchant, note or tag": "Szukaj sprzedawcy, notatki lub tagu", All: "Wszystkie", Expenses: "Wydatki", "Import statement": "Importuj wyciąg", Delete: "Usuń", "No matching transactions": "Brak pasujących transakcji", "Change the filters or log a new entry.": "Zmień filtry lub dodaj nowy wpis.",
    "YOUR SPENDING PLAN": "TWÓJ PLAN WYDATKÓW", "Monthly plan": "Plan miesięczny", "Assign a job to your money and compare the plan with actual spending.": "Zaplanuj pieniądze i porównaj plan z rzeczywistymi wydatkami.", "Copy previous month": "Kopiuj poprzedni miesiąc", "MONTHLY BUDGET": "BUDŻET MIESIĘCZNY", Save: "Zapisz", spent: "wydano", remaining: "pozostało", "assigned to categories": "przypisano do kategorii", "CATEGORY ENVELOPES": "BUDŻETY KATEGORII", unassigned: "nieprzypisane",
    "WHAT IS COMING": "CO NADCHODZI", Recurring: "Cykliczne", "Plan around subscriptions, bills and regular income.": "Uwzględniaj subskrypcje, rachunki i regularne przychody.", "Add recurring": "Dodaj cykliczne", "Unlock with Plus": "Odblokuj w Plus", "MONTHLY COMMITMENTS": "MIESIĘCZNE ZOBOWIĄZANIA", "active recurring expenses": "aktywne cykliczne wydatki", "ACTIVE ITEMS": "AKTYWNE POZYCJE", "bills and income": "rachunki i przychody", ANNUALIZED: "ROCZNIE", "estimated recurring spend": "szacowane cykliczne wydatki", "every month": "co miesiąc", "No recurring items yet": "Brak pozycji cyklicznych", "Add rent, subscriptions, salary or other repeating entries.": "Dodaj czynsz, subskrypcje, wypłatę lub inne powtarzalne wpisy.",
    "MAKE ROOM FOR WHAT MATTERS": "MIEJSCE NA TO, CO WAŻNE", Goals: "Cele", "Track several goals and see the monthly contribution needed to stay on time.": "Śledź cele i potrzebne miesięczne wpłaty.", "New goal": "Nowy cel", "More goals · Plus": "Więcej celów · Plus", "No goals yet": "Brak celów", "Create a savings goal and Trek will calculate the required pace.": "Utwórz cel oszczędnościowy, a Trek obliczy wymagane tempo.", Contribution: "Wpłata", Add: "Dodaj", "No deadline": "Bez terminu", "Target date": "Termin", "per month to stay on track": "miesięcznie, aby utrzymać tempo",
    "THE BIGGER PICTURE": "SZERSZY OBRAZ", Analytics: "Analizy", "Every chart is calculated from the selected month’s records.": "Wykresy są obliczane z danych wybranego miesiąca.", "MONTH VS PREVIOUS": "MIESIĄC VS POPRZEDNI", more: "więcej", less: "mniej", spending: "wydatków", "SAVINGS RATE": "STOPA OSZCZĘDNOŚCI", "income minus expenses": "przychody minus wydatki", "NO-SPEND DAYS": "DNI BEZ WYDATKÓW", "within the last 7 days": "w ostatnich 7 dniach", "DAILY RHYTHM": "RYTM DZIENNY", average: "średnio", "WHERE IT WENT": "NA CO WYDANO", "BUDGET VS ACTUAL": "BUDŻET VS RZECZYWISTOŚĆ", "No analytics yet": "Brak danych do analizy", "Add transactions to reveal your spending pattern.": "Dodaj transakcje, aby zobaczyć wzorzec wydatków.", Total: "Razem",
    "DIGITAL ASSETS": "AKTYWA CYFROWE", "Crypto portfolio": "Portfel kryptowalut", "Track positions and market value without sharing wallet keys.": "Śledź pozycje i wartość rynkową bez udostępniania kluczy portfela.", Refresh: "Odśwież", "Add asset": "Dodaj aktywo", "PORTFOLIO VALUE": "WARTOŚĆ PORTFELA", "live market estimate": "bieżąca wycena rynkowa", "COST BASIS": "KOSZT ZAKUPU", "from your average prices": "według średnich cen zakupu", "UNREALIZED P/L": "NIEZREALIZOWANY ZYSK/STRATA", "add purchase prices": "dodaj ceny zakupu", "24H CHANGE": "ZMIANA 24H", "weighted portfolio move": "ważona zmiana portfela", "PORTFOLIO TREND": "TREND PORTFELA", ALLOCATION: "ALOKACJA", assets: "aktywa", POSITIONS: "POZYCJE", "Your assets": "Twoje aktywa", avg: "śr.", "unrealized P/L": "niezrealizowany zysk/strata", "No crypto assets yet": "Brak aktywów krypto", "Add a position to see live value, performance and allocation.": "Dodaj pozycję, aby zobaczyć wartość, wynik i alokację.", "Add your first asset": "Dodaj pierwsze aktywo", "Price history will appear when quotes are available.": "Historia cen pojawi się, gdy notowania będą dostępne.", "Market data may be delayed. Trek tracks your portfolio and does not provide investment advice or execute trades.": "Dane rynkowe mogą być opóźnione. Trek śledzi portfel, ale nie świadczy usług doradztwa ani nie realizuje transakcji.", "Plus feature": "Funkcja Plus", "NEW POSITION": "NOWA POZYCJA", "Add a crypto asset": "Dodaj aktywo krypto", "Enter the amount you own and your average purchase price. Trek stores the position, never wallet credentials.": "Podaj ilość i średnią cenę zakupu. Trek zapisuje pozycję, nigdy dane dostępowe do portfela.", Asset: "Aktywo", Quantity: "Ilość", "Average purchase price": "Średnia cena zakupu", "Price per coin": "Cena za monetę", "Save position": "Zapisz pozycję",
    "WELCOME TO TREK": "WITAJ W TREK", "Make it your money space.": "Stwórz swoją przestrzeń finansową.", "A few details are enough to make every forecast useful from day one.": "Kilka informacji wystarczy, aby prognozy były użyteczne od pierwszego dnia.", "Your name": "Twoje imię", "Set your monthly baseline.": "Ustaw miesięczną bazę.", "Choose the currency you normally plan in and a realistic monthly spending limit.": "Wybierz walutę i realistyczny miesięczny limit wydatków.", Currency: "Waluta", "Monthly budget": "Budżet miesięczny", "Add an opening income.": "Dodaj początkowy przychód.", "Optional. Add this month’s income now, or leave the field empty and record it later.": "Opcjonalnie dodaj przychód z tego miesiąca lub zapisz go później.", "Income this month": "Przychód w tym miesiącu", Optional: "Opcjonalnie", Back: "Wstecz", Continue: "Dalej", "Preparing your dashboard…": "Przygotowujemy pulpit…", "Open my dashboard": "Otwórz mój pulpit", "Add the name you want Trek to use.": "Wpisz imię, którego ma używać Trek.", "Add a monthly budget greater than zero.": "Wpisz miesięczny budżet większy od zera.", "Setup could not be saved.": "Nie udało się zapisać ustawień.",
    "NEW GOAL": "NOWY CEL", "Give your money direction.": "Nadaj swoim pieniądzom kierunek.", Name: "Nazwa", "Emergency fund": "Fundusz awaryjny", "Target amount": "Kwota docelowa", Color: "Kolor", "Create goal": "Utwórz cel", "RECURRING ITEM": "POZYCJA CYKLICZNA", "Plan what repeats.": "Zaplanuj powtarzalne płatności.", Type: "Typ", Expense: "Wydatek", "Merchant or source": "Sprzedawca lub źródło", Amount: "Kwota", Category: "Kategoria", "Day of month": "Dzień miesiąca", "Save recurring item": "Zapisz pozycję cykliczną", "Saving…": "Zapisywanie…", "What should I change this month?": "Co powinienem zmienić w tym miesiącu?", "Which category needs attention?": "Która kategoria wymaga uwagi?", "Can I safely increase my savings goal?": "Czy mogę bezpiecznie zwiększyć cel oszczędności?", "Ask about your money pace.": "Zapytaj o tempo swoich finansów.", "Your question": "Twoje pytanie", "Thinking…": "Analizuję…",
    "Your membership and unlocked features sync automatically with your Trek account.": "Plan i odblokowane funkcje synchronizują się automatycznie z kontem Trek.", "Manage payments, invoices or cancellation through Stripe’s secure customer portal.": "Zarządzaj płatnościami, fakturami i anulowaniem w bezpiecznym portalu Stripe.", "View plan features": "Zobacz funkcje planu", "See plans": "Zobacz plany", "Manage billing": "Zarządzaj płatnościami", "Spending pace": "Tempo wydatków", "Trek signal": "Sygnał Trek", "Recent transactions": "Ostatnie transakcje", "Top goal": "Główny cel", ADMINISTRATION: "ADMINISTRACJA", "Membership access": "Dostęp do planów", "Find users and grant Start, Plus or Lifetime access from a protected server endpoint.": "Znajduj użytkowników i przyznawaj plany przez chroniony endpoint serwera.", "Open admin tools": "Otwórz narzędzia administratora", "Show amounts": "Pokaż kwoty", "Hide amounts": "Ukryj kwoty", "Budget alerts on": "Alerty budżetowe włączone", "Budget alerts off": "Alerty budżetowe wyłączone", "Download or restore transactions, goals, recurring items and crypto positions.": "Pobierz lub przywróć transakcje, cele, płatności cykliczne i pozycje krypto.", "Cloud backup tools are available with Plus or Lifetime.": "Kopie w chmurze są dostępne w planach Plus i Lifetime.", "Export data": "Eksportuj dane", "Upgrade to export": "Ulepsz, aby eksportować", "Restore backup": "Przywróć kopię", "Permanently erase your Trek account and stored financial data.": "Trwale usuń konto Trek i zapisane dane finansowe.", "Delete my account": "Usuń moje konto",
  },
  uk: {
    "SAFE TO SPEND": "МОЖНА ВИТРАТИТИ", DAY: "ДЕНЬ", "reserved for upcoming bills": "зарезервовано на майбутні рахунки", "Add transaction": "Додати транзакцію",
    SPENT: "ВИТРАЧЕНО", "MONTH-END FORECAST": "ПРОГНОЗ НА КІНЕЦЬ МІСЯЦЯ", INCOME: "ДОХІД", PLANNED: "ЗАПЛАНОВАНО", of: "з", budget: "бюджету", above: "понад", within: "у межах", "current plan": "поточного плану", "logged this month": "цього місяця", "across category envelopes": "у категоріях",
    "LAST 7 DAYS": "ОСТАННІ 7 ДНІВ", "Daily spending rhythm": "Ритм щоденних витрат", "View analytics": "Переглянути аналітику", "TREK SIGNAL": "СИГНАЛ TREK", "Your current pace is above plan": "Ваш поточний темп перевищує план", "Your current pace is inside plan": "Ваш поточний темп у межах плану", "Review plan": "Переглянути план", "Ask the coach": "Запитати коуча", "RECENT TRANSACTIONS": "ОСТАННІ ТРАНЗАКЦІЇ", "Latest activity": "Остання активність", "No activity yet": "Активності ще немає", "All transactions": "Усі транзакції", "TOP GOAL": "ГОЛОВНА ЦІЛЬ", "Create your first goal": "Створіть першу ціль", "Give your monthly plan a direction.": "Додайте напрямок місячному плану.", "Open goals": "Відкрити цілі",
    "YOUR RECORDS": "ВАШІ ЗАПИСИ", Transactions: "Транзакції", "visible entries": "видимих записів", "edit, filter or review your records.": "редагуйте, фільтруйте та перевіряйте записи.", "Search merchant, note or tag": "Пошук продавця, нотатки або тегу", All: "Усі", Expenses: "Витрати", "Import statement": "Імпортувати виписку", Delete: "Видалити", "No matching transactions": "Немає відповідних транзакцій", "Change the filters or log a new entry.": "Змініть фільтри або додайте новий запис.",
    "YOUR SPENDING PLAN": "ВАШ ПЛАН ВИТРАТ", "Monthly plan": "Місячний план", "Assign a job to your money and compare the plan with actual spending.": "Розподіліть кошти й порівняйте план із фактичними витратами.", "Copy previous month": "Копіювати минулий місяць", "MONTHLY BUDGET": "МІСЯЧНИЙ БЮДЖЕТ", Save: "Зберегти", spent: "витрачено", remaining: "залишилось", "assigned to categories": "розподілено за категоріями", "CATEGORY ENVELOPES": "БЮДЖЕТИ КАТЕГОРІЙ", unassigned: "нерозподілено",
    "WHAT IS COMING": "ЩО ПОПЕРЕДУ", Recurring: "Регулярні", "Plan around subscriptions, bills and regular income.": "Враховуйте підписки, рахунки та регулярні доходи.", "Add recurring": "Додати регулярну", "Unlock with Plus": "Відкрити з Plus", "MONTHLY COMMITMENTS": "МІСЯЧНІ ЗОБОВ’ЯЗАННЯ", "active recurring expenses": "активні регулярні витрати", "ACTIVE ITEMS": "АКТИВНІ ПОЗИЦІЇ", "bills and income": "рахунки й доходи", ANNUALIZED: "ЗА РІК", "estimated recurring spend": "очікувані регулярні витрати", "every month": "щомісяця", "No recurring items yet": "Регулярних записів ще немає", "Add rent, subscriptions, salary or other repeating entries.": "Додайте оренду, підписки, зарплату чи інші повторювані записи.",
    "MAKE ROOM FOR WHAT MATTERS": "МІСЦЕ ДЛЯ ВАЖЛИВОГО", Goals: "Цілі", "Track several goals and see the monthly contribution needed to stay on time.": "Відстежуйте цілі та потрібні щомісячні внески.", "New goal": "Нова ціль", "More goals · Plus": "Більше цілей · Plus", "No goals yet": "Цілей ще немає", "Create a savings goal and Trek will calculate the required pace.": "Створіть ціль заощаджень, і Trek розрахує потрібний темп.", Contribution: "Внесок", Add: "Додати", "No deadline": "Без терміну", "Target date": "Термін", "per month to stay on track": "на місяць, щоб тримати темп",
    "THE BIGGER PICTURE": "ШИРША КАРТИНА", Analytics: "Аналітика", "Every chart is calculated from the selected month’s records.": "Усі графіки розраховано з даних вибраного місяця.", "MONTH VS PREVIOUS": "МІСЯЦЬ VS МИНУЛИЙ", more: "більше", less: "менше", spending: "витрат", "SAVINGS RATE": "РІВЕНЬ ЗАОЩАДЖЕНЬ", "income minus expenses": "дохід мінус витрати", "NO-SPEND DAYS": "ДНІ БЕЗ ВИТРАТ", "within the last 7 days": "за останні 7 днів", "DAILY RHYTHM": "ДЕННИЙ РИТМ", average: "у середньому", "WHERE IT WENT": "КУДИ ПІШЛИ КОШТИ", "BUDGET VS ACTUAL": "БЮДЖЕТ VS ФАКТ", "No analytics yet": "Даних для аналітики ще немає", "Add transactions to reveal your spending pattern.": "Додайте транзакції, щоб побачити структуру витрат.", Total: "Разом",
    "DIGITAL ASSETS": "ЦИФРОВІ АКТИВИ", "Crypto portfolio": "Криптопортфель", "Track positions and market value without sharing wallet keys.": "Відстежуйте позиції та ринкову вартість без передачі ключів гаманця.", Refresh: "Оновити", "Add asset": "Додати актив", "PORTFOLIO VALUE": "ВАРТІСТЬ ПОРТФЕЛЯ", "live market estimate": "поточна ринкова оцінка", "COST BASIS": "ВАРТІСТЬ ПРИДБАННЯ", "from your average prices": "за середніми цінами придбання", "UNREALIZED P/L": "НЕРЕАЛІЗОВАНИЙ ПРИБУТОК/ЗБИТОК", "add purchase prices": "додайте ціни придбання", "24H CHANGE": "ЗМІНА ЗА 24 Г", "weighted portfolio move": "зважена зміна портфеля", "PORTFOLIO TREND": "ДИНАМІКА ПОРТФЕЛЯ", ALLOCATION: "РОЗПОДІЛ", assets: "активів", POSITIONS: "ПОЗИЦІЇ", "Your assets": "Ваші активи", avg: "сер.", "unrealized P/L": "нереалізований прибуток/збиток", "No crypto assets yet": "Криптоактивів ще немає", "Add a position to see live value, performance and allocation.": "Додайте позицію, щоб побачити вартість, результат і розподіл.", "Add your first asset": "Додати перший актив", "Price history will appear when quotes are available.": "Історія цін з’явиться, коли будуть доступні котирування.", "Market data may be delayed. Trek tracks your portfolio and does not provide investment advice or execute trades.": "Ринкові дані можуть надходити із затримкою. Trek відстежує портфель, але не надає інвестиційних порад і не виконує угод.", "Plus feature": "Функція Plus", "NEW POSITION": "НОВА ПОЗИЦІЯ", "Add a crypto asset": "Додати криптоактив", "Enter the amount you own and your average purchase price. Trek stores the position, never wallet credentials.": "Вкажіть кількість і середню ціну придбання. Trek зберігає позицію, але ніколи не зберігає дані доступу до гаманця.", Asset: "Актив", Quantity: "Кількість", "Average purchase price": "Середня ціна придбання", "Price per coin": "Ціна за монету", "Save position": "Зберегти позицію",
    "WELCOME TO TREK": "ВІТАЄМО У TREK", "Make it your money space.": "Створіть свій фінансовий простір.", "A few details are enough to make every forecast useful from day one.": "Кількох деталей достатньо, щоб прогнози були корисними з першого дня.", "Your name": "Ваше ім’я", "Set your monthly baseline.": "Встановіть місячну основу.", "Choose the currency you normally plan in and a realistic monthly spending limit.": "Оберіть основну валюту та реалістичний місячний ліміт витрат.", Currency: "Валюта", "Monthly budget": "Місячний бюджет", "Add an opening income.": "Додайте початковий дохід.", "Optional. Add this month’s income now, or leave the field empty and record it later.": "За бажанням додайте дохід цього місяця або запишіть його пізніше.", "Income this month": "Дохід цього місяця", Optional: "Необов’язково", Back: "Назад", Continue: "Далі", "Preparing your dashboard…": "Готуємо огляд…", "Open my dashboard": "Відкрити огляд", "Add the name you want Trek to use.": "Вкажіть ім’я, яке використовуватиме Trek.", "Add a monthly budget greater than zero.": "Вкажіть місячний бюджет, більший за нуль.", "Setup could not be saved.": "Не вдалося зберегти налаштування.",
    "NEW GOAL": "НОВА ЦІЛЬ", "Give your money direction.": "Додайте напрямок своїм коштам.", Name: "Назва", "Emergency fund": "Резервний фонд", "Target amount": "Цільова сума", Color: "Колір", "Create goal": "Створити ціль", "RECURRING ITEM": "РЕГУЛЯРНИЙ ЗАПИС", "Plan what repeats.": "Заплануйте повторювані платежі.", Type: "Тип", Expense: "Витрата", "Merchant or source": "Продавець або джерело", Amount: "Сума", Category: "Категорія", "Day of month": "День місяця", "Save recurring item": "Зберегти регулярний запис", "Saving…": "Збереження…", "What should I change this month?": "Що варто змінити цього місяця?", "Which category needs attention?": "Яка категорія потребує уваги?", "Can I safely increase my savings goal?": "Чи можу я безпечно збільшити ціль заощаджень?", "Ask about your money pace.": "Запитайте про темп своїх фінансів.", "Your question": "Ваше питання", "Thinking…": "Аналізую…",
    "Your membership and unlocked features sync automatically with your Trek account.": "Підписка й доступні функції автоматично синхронізуються з акаунтом Trek.", "Manage payments, invoices or cancellation through Stripe’s secure customer portal.": "Керуйте платежами, рахунками та скасуванням у захищеному порталі Stripe.", "View plan features": "Переглянути функції плану", "See plans": "Переглянути плани", "Manage billing": "Керувати оплатою", "Spending pace": "Темп витрат", "Trek signal": "Сигнал Trek", "Recent transactions": "Останні транзакції", "Top goal": "Головна ціль", ADMINISTRATION: "АДМІНІСТРУВАННЯ", "Membership access": "Доступ до підписок", "Find users and grant Start, Plus or Lifetime access from a protected server endpoint.": "Знаходьте користувачів і надавайте доступ Start, Plus або Lifetime через захищений сервер.", "Open admin tools": "Відкрити інструменти адміністратора", "Show amounts": "Показати суми", "Hide amounts": "Приховати суми", "Budget alerts on": "Бюджетні сповіщення ввімкнено", "Budget alerts off": "Бюджетні сповіщення вимкнено", "Download or restore transactions, goals, recurring items and crypto positions.": "Завантажуйте або відновлюйте транзакції, цілі, регулярні записи та криптопозиції.", "Cloud backup tools are available with Plus or Lifetime.": "Хмарні резервні копії доступні в Plus або Lifetime.", "Export data": "Експортувати дані", "Upgrade to export": "Оновити для експорту", "Restore backup": "Відновити копію", "Permanently erase your Trek account and stored financial data.": "Назавжди видалити акаунт Trek і збережені фінансові дані.", "Delete my account": "Видалити мій акаунт",
  },
};

export const ui = (locale, text) => PAGE_TRANSLATIONS[locale]?.[text] || text;

const CATEGORY_TRANSLATIONS = {
  pl: { Groceries: "Zakupy spożywcze", Transport: "Transport", Subscriptions: "Subskrypcje", Coffee: "Kawa", Shopping: "Zakupy", Housing: "Mieszkanie", Health: "Zdrowie", Fun: "Rozrywka", Other: "Inne" },
  uk: { Groceries: "Продукти", Transport: "Транспорт", Subscriptions: "Підписки", Coffee: "Кава", Shopping: "Покупки", Housing: "Житло", Health: "Здоров’я", Fun: "Розваги", Other: "Інше" },
};
export const categoryLabel = (locale, category) => CATEGORY_TRANSLATIONS[locale]?.[category] || category;
