export const PUBLIC_COPY = {
  en: {
    nav: ["Product", "How It Works", "Pricing", "FAQ"], login: "Log In", start: "Start Free",
    hero: { eyebrow: "NO BANK LOGINS. NO NOISE.", lines: ["Money, made", "clear.", "Stay in control."], body: "Trek does more than track spending. It shows what is safe to spend today without breaking the month.", primary: "Take Control", demo: "See How It Works", private: "Your Data Stays Yours", art: { safe: "SAFE TO SPEND TODAY", after: "after planned expenses", pace: "Keep the pace", inside: "You are inside plan", goal: "Summer trip", complete: "complete" } },
    proof: ["A CLEAR SIGNAL FOR EVERY MONEY DECISION.", "to get started", "bank logins", "currencies included"],
    product: { eyebrow: "INSIDE TREK", lines: ["One screen.", "One clear next move."], body: "See your whole picture in seconds, then know exactly what to change this month.", open: "Open dashboard", preview: { overview: "Overview", accounts: "Accounts", transactions: "Transactions", calendar: "Calendar", automation: "Automation", month: "SEPTEMBER · 2026", title: "Your money today", safe: "SAFE TO SPEND TODAY", perDay: "per day", reserved: "Upcoming bills already reserved", balance: "Total balance", pulse: "money pulse", chartLabel: "Spending over the last 12 months", coffee: "Coffee Room", market: "Market", lastSeven: "LAST 7 DAYS", signal: "SMART INSIGHT", insight: "Shopping is close to its limit.", insightBody: "You have 58 € left in this category.", goal: "TOP GOAL", goalName: "Summer trip" } },
    how: { eyebrow: "LESS ADMIN", lines: ["Less counting.", "More direction."], steps: [["Add it in five seconds", "Type “coffee 85” or scan a receipt. Trek turns it into a clear record."], ["See your actual pace", "Not just what you spent — whether your plan will last to the end of the month."], ["Act on a signal", "A concrete number: what to trim and how much it gives back to you."]] },
    pricing: { eyebrow: "SIMPLE PRICING", lines: ["Build the habit first.", "Go deeper when ready."], body: "Start without a card. Upgrade only when deeper planning and automation become useful.", popular: "MOST POPULAR", cards: [
      ["START", "0 €", "/ forever", "Get a clear monthly baseline.", ["Manual tracking and receipt scan", "Monthly plan and one goal", "Two crypto positions", "Secure cloud account"], "Start free"],
      ["PLUS", "6 €", "/ month", "Automate the routine and see deeper patterns.", ["Recurring bills and unlimited goals", "Advanced interactive analytics", "Trek Coach and data export", "Unlimited crypto portfolio"], "Choose Plus"],
      ["LIFETIME", "149 €", "/ once", "Own every Trek feature with one payment.", ["Every Plus feature", "CSV and PDF bank import", "Historical exchange-rate conversion", "Lifetime access"], "Choose Lifetime"]
    ], open: "Open account", manage: "Manage plan" },
    info: [["Private by design", "No bank credentials. Clear data boundaries."], ["Signals, not noise", "Trend and category views that lead to one next move."], ["Built for real goals", "Keep daily decisions aligned with what matters."]],
    faq: { eyebrow: "QUESTIONS, ANSWERED", lines: ["Clear money needs", "clear answers."], body: "Everything you need to know before starting your first month.", items: [["What does “safe to spend” mean?", "It is the amount you can use today after your monthly plan, regular costs and active goals are taken into account."], ["Do I need to connect a bank account?", "No. Trek starts with manual expenses and income, so your banking credentials are never requested."], ["Can I change currency later?", "Yes. Choose UAH, PLN, EUR or USD in Settings. Your active currency can be changed at any time."], ["What will a membership unlock?", "Start covers daily tracking. Plus adds advanced insights, exports and automation; Lifetime includes every feature permanently."], ["Is Trek ready for real payments and accounts?", "Yes. Accounts are secured through Supabase and paid plans use Stripe Checkout and its customer portal. Trek never stores payment card details."]] },
    footer: { motto: "Your money. Your pace. Your data.", privacy: "Privacy", cookies: "Cookies", terms: "Terms", support: "Support" },
    video: { eyebrow: "TREK IN ACTION", title: "See how Trek works." },
    cookie: { title: "Essential storage only", body: "Trek uses necessary session and preference storage. No advertising or analytics trackers are active.", details: "Cookie details", ok: "Got it" },
    auth: { private: "PRIVATE MONEY SPACE", hero: ["Your money.", "Your pace."], brandBody: "Simple tracking, clear budgets and signals you can act on.", secure: "Protected by secure account sessions", eyebrow: "TREK ACCOUNT", titles: { login: "Welcome back", signup: "Create your account", reset: "Reset your password" }, copies: { login: "Your money rhythm is waiting.", signup: "Start building a clearer money habit.", reset: "We will send you a secure reset link." }, unavailable: "Add the Supabase environment variables in Railway to activate secure sign-in.", name: "Full name", namePlaceholder: "Your name", email: "Email", password: "Password", passwordPlaceholder: "At least 6 characters", wait: "Please wait…", create: "Create account", reset: "Send reset link", signIn: "Sign in", forgot: "Forgot password?", existing: "Already have an account?", new: "New to Trek?", back: "Back to sign in", createLink: "Create an account", legalStart: "I agree to the", legalAnd: "and acknowledge the", terms: "Terms", privacy: "Privacy Notice", securityCheck: "Complete the security check.", suspicious: "Please wait a moment and try again.", confirm: "Check your email to confirm the account, then sign in.", resetSent: "If this address exists, a password-reset email is on its way." }
  },
  pl: {
    nav: ["Produkt", "Jak to działa", "Cennik", "FAQ"], login: "Zaloguj się", start: "Zacznij bezpłatnie",
    hero: { eyebrow: "BEZ LOGOWANIA DO BANKU. BEZ SZUMU.", lines: ["Finanse, które", "są jasne.", "Pełna kontrola."], body: "Trek nie tylko śledzi wydatki. Pokazuje, ile możesz bezpiecznie wydać dzisiaj, nie zaburzając planu miesiąca.", primary: "Przejmij kontrolę", demo: "Zobacz, jak to działa", private: "Twoje dane należą do Ciebie", art: { safe: "BEZPIECZNIE DO WYDANIA", after: "po zaplanowanych wydatkach", pace: "Utrzymaj tempo", inside: "Plan jest pod kontrolą", goal: "Letnia podróż", complete: "ukończono" } },
    proof: ["JASNY SYGNAŁ DLA KAŻDEJ DECYZJI FINANSOWEJ.", "do rozpoczęcia", "logowań do banku", "obsługiwane waluty"],
    product: { eyebrow: "WEWNĄTRZ TREK", lines: ["Jeden ekran.", "Jeden jasny kolejny krok."], body: "Zobacz cały obraz w kilka sekund i od razu wiedz, co zmienić w tym miesiącu.", open: "Otwórz panel", preview: { overview: "Pulpit", accounts: "Konta", transactions: "Transakcje", calendar: "Kalendarz", automation: "Automatyzacje", month: "WRZESIEŃ · 2026", title: "Twoje finanse dzisiaj", safe: "BEZPIECZNIE DO WYDANIA", perDay: "dziennie", reserved: "Nadchodzące rachunki są uwzględnione", balance: "Łączne saldo", pulse: "puls finansów", chartLabel: "Wydatki z ostatnich 12 miesięcy", coffee: "Kawiarnia", market: "Sklep", lastSeven: "OSTATNIE 7 DNI", signal: "INTELIGENTNA WSKAZÓWKA", insight: "Zakupy zbliżają się do limitu.", insightBody: "W tej kategorii pozostało 58 €.", goal: "GŁÓWNY CEL", goalName: "Letnia podróż" } },
    how: { eyebrow: "MNIEJ ADMINISTRACJI", lines: ["Mniej liczenia.", "Więcej kierunku."], steps: [["Dodaj w pięć sekund", "Wpisz „kawa 85” lub zeskanuj paragon. Trek utworzy czytelny zapis."], ["Zobacz swoje rzeczywiste tempo", "Nie tylko ile wydajesz — także czy plan wystarczy do końca miesiąca."], ["Działaj na podstawie sygnału", "Konkretna liczba: co ograniczyć i ile dzięki temu odzyskasz."]] },
    pricing: { eyebrow: "PROSTY CENNIK", lines: ["Najpierw zbuduj nawyk.", "Rozwijaj się, gdy będziesz gotowy."], body: "Zacznij bez karty. Przejdź wyżej, gdy planowanie i automatyzacja staną się przydatne.", popular: "NAJPOPULARNIEJSZY", cards: [
      ["START", "0 €", "/ na zawsze", "Poznaj swój miesięczny punkt odniesienia.", ["Ręczne wpisy i skan paragonu", "Plan miesiąca i jeden cel", "Dwie pozycje krypto", "Bezpieczne konto w chmurze"], "Zacznij bezpłatnie"],
      ["PLUS", "6 €", "/ miesiąc", "Automatyzuj rutynę i poznaj głębsze wzorce.", ["Cykliczne opłaty i cele bez limitu", "Zaawansowane interaktywne analizy", "Trek Coach i eksport danych", "Portfel krypto bez limitu"], "Wybierz Plus"],
      ["LIFETIME", "149 €", "/ jednorazowo", "Wszystkie funkcje Trek za jedną opłatą.", ["Wszystkie funkcje Plus", "Import wyciągów CSV i PDF", "Historyczne przeliczanie walut", "Dostęp bezterminowy"], "Wybierz Lifetime"]
    ], open: "Otwórz konto", manage: "Zarządzaj planem" },
    info: [["Prywatność od podstaw", "Bez danych logowania do banku. Jasne granice danych."], ["Sygnały zamiast szumu", "Trendy i kategorie prowadzące do konkretnej decyzji."], ["Dla prawdziwych celów", "Codzienne decyzje zgodne z tym, co ważne."]],
    faq: { eyebrow: "PYTANIA I ODPOWIEDZI", lines: ["Jasne finanse potrzebują", "jasnych odpowiedzi."], body: "Wszystko, co warto wiedzieć przed rozpoczęciem pierwszego miesiąca.", items: [["Co oznacza „bezpiecznie do wydania”?", "To kwota, którą możesz wykorzystać dzisiaj po uwzględnieniu planu miesiąca, stałych kosztów i aktywnych celów."], ["Czy muszę podłączać konto bankowe?", "Nie. Trek zaczyna od ręcznych wydatków i przychodów, dlatego nigdy nie prosi o dane logowania do banku."], ["Czy mogę później zmienić walutę?", "Tak. W Ustawieniach wybierz UAH, PLN, EUR lub USD. Aktywną walutę możesz zmienić w dowolnym momencie."], ["Co daje płatny plan?", "Start obejmuje codzienne śledzenie. Plus dodaje analizy, eksport i automatyzację, a Lifetime wszystkie funkcje bezterminowo."], ["Czy Trek obsługuje prawdziwe płatności i konta?", "Tak. Konta zabezpiecza Supabase, a płatne plany korzystają ze Stripe Checkout i portalu klienta. Trek nie przechowuje danych kart."]] },
    footer: { motto: "Twoje pieniądze. Twoje tempo. Twoje dane.", privacy: "Prywatność", cookies: "Cookies", terms: "Regulamin", support: "Pomoc" },
    video: { eyebrow: "TREK W PRAKTYCE", title: "Zobacz, jak działa Trek." },
    cookie: { title: "Tylko niezbędne dane", body: "Trek używa niezbędnej pamięci sesji i preferencji. Reklamowe ani analityczne trackery nie są aktywne.", details: "Szczegóły cookies", ok: "Rozumiem" },
    auth: { private: "PRYWATNA PRZESTRZEŃ FINANSOWA", hero: ["Twoje pieniądze.", "Twoje tempo."], brandBody: "Proste śledzenie, jasne budżety i sygnały, na podstawie których możesz działać.", secure: "Chronione przez bezpieczne sesje konta", eyebrow: "KONTO TREK", titles: { login: "Witaj ponownie", signup: "Utwórz konto", reset: "Zresetuj hasło" }, copies: { login: "Twój rytm finansowy czeka.", signup: "Zacznij budować lepsze nawyki finansowe.", reset: "Wyślemy bezpieczny link resetujący." }, unavailable: "Dodaj zmienne Supabase w Railway, aby aktywować bezpieczne logowanie.", name: "Imię i nazwisko", namePlaceholder: "Twoje imię", email: "E-mail", password: "Hasło", passwordPlaceholder: "Co najmniej 6 znaków", wait: "Proszę czekać…", create: "Utwórz konto", reset: "Wyślij link", signIn: "Zaloguj się", forgot: "Nie pamiętasz hasła?", existing: "Masz już konto?", new: "Pierwszy raz w Trek?", back: "Wróć do logowania", createLink: "Utwórz konto", legalStart: "Akceptuję", legalAnd: "i potwierdzam zapoznanie z", terms: "Regulaminem", privacy: "Polityką prywatności", securityCheck: "Ukończ kontrolę bezpieczeństwa.", suspicious: "Odczekaj chwilę i spróbuj ponownie.", confirm: "Potwierdź konto przez wiadomość e-mail, a następnie się zaloguj.", resetSent: "Jeśli ten adres istnieje, wysłaliśmy wiadomość z linkiem do resetowania hasła." }
  },
  uk: {
    nav: ["Продукт", "Як це працює", "Тарифи", "FAQ"], login: "Увійти", start: "Почати безкоштовно",
    hero: { eyebrow: "БЕЗ ДОСТУПУ ДО БАНКУ. БЕЗ ШУМУ.", lines: ["Фінанси стають", "зрозумілими.", "Усе під контролем."], body: "Trek не лише відстежує витрати. Він показує, скільки безпечно витратити сьогодні, не порушуючи план місяця.", primary: "Взяти під контроль", demo: "Подивитися, як це працює", private: "Ваші дані належать вам", art: { safe: "БЕЗПЕЧНО ВИТРАТИТИ", after: "після запланованих витрат", pace: "Тримайте темп", inside: "План під контролем", goal: "Літня подорож", complete: "виконано" } },
    proof: ["ЧІТКИЙ СИГНАЛ ДЛЯ КОЖНОГО ФІНАНСОВОГО РІШЕННЯ.", "до початку роботи", "входів до банку", "підтримувані валюти"],
    product: { eyebrow: "УСЕРЕДИНІ TREK", lines: ["Один екран.", "Один зрозумілий наступний крок."], body: "Побачте всю картину за кілька секунд і зрозумійте, що змінити цього місяця.", open: "Відкрити панель", preview: { overview: "Огляд", accounts: "Рахунки", transactions: "Транзакції", calendar: "Календар", automation: "Автоматизація", month: "ВЕРЕСЕНЬ · 2026", title: "Ваші фінанси сьогодні", safe: "БЕЗПЕЧНО ВИТРАТИТИ", perDay: "на день", reserved: "Майбутні рахунки вже враховано", balance: "Загальний баланс", pulse: "пульс фінансів", chartLabel: "Витрати за останні 12 місяців", coffee: "Кав’ярня", market: "Магазин", lastSeven: "ОСТАННІ 7 ДНІВ", signal: "РОЗУМНА ПІДКАЗКА", insight: "Покупки наближаються до ліміту.", insightBody: "У цій категорії залишилося 58 €.", goal: "ГОЛОВНА ЦІЛЬ", goalName: "Літня подорож" } },
    how: { eyebrow: "МЕНШЕ РУТИНИ", lines: ["Менше підрахунків.", "Більше напряму."], steps: [["Додайте за п’ять секунд", "Введіть «кава 85» або відскануйте чек. Trek створить зрозумілий запис."], ["Побачте реальний темп", "Не лише скільки витрачено — а й чи вистачить плану до кінця місяця."], ["Дійте за сигналом", "Конкретне число: що скоротити та скільки це поверне вам."]] },
    pricing: { eyebrow: "ПРОСТІ ТАРИФИ", lines: ["Спочатку сформуйте звичку.", "Розширюйте можливості, коли будете готові."], body: "Почніть без картки. Переходьте далі, коли глибше планування й автоматизація стануть корисними.", popular: "НАЙПОПУЛЯРНІШИЙ", cards: [
      ["START", "0 €", "/ назавжди", "Створіть зрозумілу основу місячного бюджету.", ["Ручний облік і сканування чеків", "Місячний план і одна ціль", "Дві криптопозиції", "Захищений хмарний акаунт"], "Почати безкоштовно"],
      ["PLUS", "6 €", "/ місяць", "Автоматизуйте рутину та знаходьте закономірності.", ["Регулярні платежі та необмежені цілі", "Розширена інтерактивна аналітика", "Trek Coach та експорт даних", "Необмежений криптопортфель"], "Обрати Plus"],
      ["LIFETIME", "149 €", "/ одноразово", "Усі функції Trek за один платіж.", ["Усі функції Plus", "Імпорт банківських CSV і PDF", "Конвертація за історичним курсом", "Довічний доступ"], "Обрати Lifetime"]
    ], open: "Відкрити акаунт", manage: "Керувати тарифом" },
    info: [["Приватність за задумом", "Без банківських логінів. Чіткі межі даних."], ["Сигнали замість шуму", "Тренди й категорії, що ведуть до конкретного рішення."], ["Для справжніх цілей", "Щоденні рішення відповідно до того, що важливо."]],
    faq: { eyebrow: "ПИТАННЯ ТА ВІДПОВІДІ", lines: ["Зрозумілі фінанси потребують", "зрозумілих відповідей."], body: "Усе, що варто знати перед початком першого місяця.", items: [["Що означає «безпечно витратити»?", "Це сума, яку можна використати сьогодні після врахування місячного плану, регулярних витрат та активних цілей."], ["Чи потрібно підключати банківський рахунок?", "Ні. Trek починає з ручного обліку витрат і доходів, тому ніколи не запитує банківські дані для входу."], ["Чи можна пізніше змінити валюту?", "Так. Виберіть UAH, PLN, EUR або USD у Налаштуваннях. Активну валюту можна змінити будь-коли."], ["Що відкриває підписка?", "Start охоплює щоденний облік. Plus додає аналітику, експорт і автоматизацію, а Lifetime — усі функції назавжди."], ["Чи готовий Trek до реальних платежів та акаунтів?", "Так. Акаунти захищені через Supabase, а платні тарифи використовують Stripe Checkout і портал клієнта. Trek не зберігає дані платіжних карток."]] },
    footer: { motto: "Ваші гроші. Ваш темп. Ваші дані.", privacy: "Приватність", cookies: "Cookies", terms: "Умови", support: "Підтримка" },
    video: { eyebrow: "TREK У ДІЇ", title: "Подивіться, як працює Trek." },
    cookie: { title: "Лише необхідне зберігання", body: "Trek використовує необхідне зберігання сесії та налаштувань. Рекламні й аналітичні трекери не активні.", details: "Докладніше про cookies", ok: "Зрозуміло" },
    auth: { private: "ПРИВАТНИЙ ФІНАНСОВИЙ ПРОСТІР", hero: ["Ваші гроші.", "Ваш темп."], brandBody: "Простий облік, зрозумілі бюджети та сигнали, за якими можна діяти.", secure: "Захищено безпечними сесіями акаунта", eyebrow: "АКАУНТ TREK", titles: { login: "З поверненням", signup: "Створіть акаунт", reset: "Скинути пароль" }, copies: { login: "Ваш фінансовий ритм чекає.", signup: "Почніть формувати зрозуміліші фінансові звички.", reset: "Ми надішлемо захищене посилання для скидання." }, unavailable: "Додайте змінні Supabase у Railway, щоб активувати безпечний вхід.", name: "Повне ім’я", namePlaceholder: "Ваше ім’я", email: "Електронна пошта", password: "Пароль", passwordPlaceholder: "Щонайменше 6 символів", wait: "Зачекайте…", create: "Створити акаунт", reset: "Надіслати посилання", signIn: "Увійти", forgot: "Забули пароль?", existing: "Уже маєте акаунт?", new: "Вперше у Trek?", back: "Назад до входу", createLink: "Створити акаунт", legalStart: "Я погоджуюся з", legalAnd: "і підтверджую, що ознайомився(-лася) з", terms: "Умовами", privacy: "Політикою приватності", securityCheck: "Пройдіть перевірку безпеки.", suspicious: "Зачекайте трохи та спробуйте ще раз.", confirm: "Підтвердьте акаунт через електронну пошту, а потім увійдіть.", resetSent: "Якщо така адреса існує, ми надіслали лист для скидання пароля." }
  }
};
